version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins1
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - /home/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker