apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: order
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 192.168.126.146:80/repo/order:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: order
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - port: 8084
      targetPort: 8083
  type: NodePort
